repos:
  # All
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml

  # Server
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.3.0
    hooks:
      - id: golangci-lint
        files: \.go$

  # Client
  - repo: https://github.com/eslint/eslint
    rev: v9.32.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        config: /client
