services:
  redis:
    container_name: weather_cache
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  server:
    container_name: weather_server
    build: 
      context: ./server
    environment:
      - MODE=${MODE}
    ports:
      - "8080:8080"
    depends_on:
      - redis

  client:
    container_name: weather_client
    build: 
      context: ./client
    environment:  # For future use
      - MODE=${MODE}
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ./client/nginx.conf.template:/etc/nginx/nginx.conf.template
    env_file:
      - ./client/.env.development.local
    

volumes:
  redis_data:
    driver: local
