services:
  redis:
    container_name: weather_cache
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  server:
    container_name: weather_server
    build: ./server
    environment:
      - MODE=${MODE}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    develop:
      watch:
        - path: ./server
          action: rebuild

  client:
    container_name: weather_client
    build: ./client
    environment:
      - MODE=${MODE}
    ports:
      - "3000:80"
    depends_on:
      - server
    develop:
      watch:
        - path: ./client
          action: rebuild
    
volumes:
  redis_data:
    driver: local
