services:
  server:
    container_name: weather_server
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env.development
    depends_on:
      - redis

  redis:
    container_name: weather_cache
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  client:
    container_name: weather_client
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

volumes:
  redis_data:
    driver: local
